/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameburza;

/**
 *
 * @author Jhan Steven Cruz
 */
public class CartUI extends javax.swing.JFrame {

    /**
     * Creates new form CartUI
     */
    public CartUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CartUIPanel = new javax.swing.JPanel();
        CartLowerUIPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        TotalCartLabel = new javax.swing.JLabel();
        TotalCartLabel1 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CartUpperUiPanel = new javax.swing.JPanel();
        CartLabel = new javax.swing.JLabel();
        ItemsLabel = new javax.swing.JLabel();
        EditCartButton = new javax.swing.JButton();
        CartUIHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(184, 30, 38));

        CartLowerUIPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox1.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        jCheckBox1.setText("Select all");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        TotalCartLabel.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        TotalCartLabel.setText("Total:");

        TotalCartLabel1.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        TotalCartLabel1.setText("$0");

        CheckOutButton.setBackground(new java.awt.Color(184, 30, 38));
        CheckOutButton.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        CheckOutButton.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutButton.setText("CHECK OUT");
        CheckOutButton.setBorderPainted(false);
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CartLowerUIPanelLayout = new javax.swing.GroupLayout(CartLowerUIPanel);
        CartLowerUIPanel.setLayout(CartLowerUIPanelLayout);
        CartLowerUIPanelLayout.setHorizontalGroup(
            CartLowerUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartLowerUIPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(TotalCartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalCartLabel1)
                .addGap(18, 18, 18)
                .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CartLowerUIPanelLayout.setVerticalGroup(
            CartLowerUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CartLowerUIPanelLayout.createSequentialGroup()
                .addGroup(CartLowerUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(TotalCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalCartLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Products", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel.setViewportView(jTable1);

        javax.swing.GroupLayout CartUIPanelLayout = new javax.swing.GroupLayout(CartUIPanel);
        CartUIPanel.setLayout(CartUIPanelLayout);
        CartUIPanelLayout.setHorizontalGroup(
            CartUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartUIPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CartUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CartLowerUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPanel)))
        );
        CartUIPanelLayout.setVerticalGroup(
            CartUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CartUIPanelLayout.createSequentialGroup()
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CartLowerUIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CartUpperUiPanel.setBackground(new java.awt.Color(184, 30, 38));

        CartLabel.setBackground(new java.awt.Color(255, 255, 255));
        CartLabel.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        CartLabel.setForeground(new java.awt.Color(255, 255, 255));
        CartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartLabel.setText("Shopping Cart");
        CartLabel.setToolTipText("");

        ItemsLabel.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        ItemsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ItemsLabel.setText("(NO. of Items)");

        EditCartButton.setBackground(new java.awt.Color(180, 30, 38));
        EditCartButton.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        EditCartButton.setForeground(new java.awt.Color(255, 255, 255));
        EditCartButton.setText("EDIT");
        EditCartButton.setBorderPainted(false);
        EditCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditCartButtonActionPerformed(evt);
            }
        });

        CartUIHomeButton.setBackground(new java.awt.Color(184, 30, 38));
        CartUIHomeButton.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        CartUIHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        CartUIHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gameburza50x50_1.png"))); // NOI18N
        CartUIHomeButton.setText("GAMEBURZA");
        CartUIHomeButton.setBorder(null);
        CartUIHomeButton.setBorderPainted(false);
        CartUIHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartUIHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CartUpperUiPanelLayout = new javax.swing.GroupLayout(CartUpperUiPanel);
        CartUpperUiPanel.setLayout(CartUpperUiPanelLayout);
        CartUpperUiPanelLayout.setHorizontalGroup(
            CartUpperUiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartUpperUiPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CartUIHomeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemsLabel)
                .addGap(132, 132, 132)
                .addComponent(EditCartButton)
                .addGap(30, 30, 30))
        );
        CartUpperUiPanelLayout.setVerticalGroup(
            CartUpperUiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartUpperUiPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(CartUpperUiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemsLabel)
                    .addComponent(EditCartButton)
                    .addComponent(CartUIHomeButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CartUpperUiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CartUIPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CartUpperUiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CartUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void EditCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditCartButtonActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_EditCartButtonActionPerformed

    private void CartUIHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartUIHomeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CartUIHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CartLabel;
    private javax.swing.JPanel CartLowerUIPanel;
    private javax.swing.JButton CartUIHomeButton;
    private javax.swing.JPanel CartUIPanel;
    private javax.swing.JPanel CartUpperUiPanel;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton EditCartButton;
    private javax.swing.JLabel ItemsLabel;
    private javax.swing.JLabel TotalCartLabel;
    private javax.swing.JLabel TotalCartLabel1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
