/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameburza;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhan Steven Cruz
 */
public class GenerateReceipt extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReceipt
     */
    public GenerateReceipt() {
        initComponents();
        
    }
    
    public void initTable(){
        DefaultTableModel recTab = (DefaultTableModel) jTable1.getModel();
        recTab.setRowCount(0);
        for(int i = 0; i < GameBurza.cart.size(); i++){
            recTab.addRow(new String[]{GameBurza.cart.get(i).title, String.valueOf(GameBurza.cart.get(i).price)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReceiptLogo = new javax.swing.JLabel();
        ReceiptBrandName = new javax.swing.JLabel();
        ReceiptTrailingLines = new javax.swing.JLabel();
        ReceiptQuote = new javax.swing.JLabel();
        ReceiptAddress = new javax.swing.JLabel();
        ReceiptTrailingLines1 = new javax.swing.JLabel();
        ReceiptTrailingLines20 = new javax.swing.JLabel();
        ReceiptGrandTotalLabel = new javax.swing.JLabel();
        ReceiptItemLabel2 = new javax.swing.JLabel();
        ReceiptPaymentMethodLabel = new javax.swing.JLabel();
        GCASHitemLabel = new javax.swing.JLabel();
        ReceiptTrailingLines21 = new javax.swing.JLabel();
        ThankYouLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GrandTotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReceiptLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameburza50x50.png"))); // NOI18N
        ReceiptLogo.setText("jLabel1");

        ReceiptBrandName.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        ReceiptBrandName.setText("GAMEBURZA");

        ReceiptTrailingLines.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines.setText("------------------------------------");

        ReceiptQuote.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptQuote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptQuote.setText("CLICK IT, PLAY IT, OWN IT!");

        ReceiptAddress.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptAddress.setText("<html><div style=\"text-align: center;\">     704 Boni Avenue,  Barangay Malamig,<br>     Mandaluyong City, Metro Manila,<br>     Philippines </div></html>");

        ReceiptTrailingLines1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines1.setText("------------------------------------");

        ReceiptTrailingLines20.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines20.setText("------------------------------------");

        ReceiptGrandTotalLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptGrandTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReceiptGrandTotalLabel.setText("GRAND TOTAL:");

        ReceiptItemLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptItemLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ReceiptPaymentMethodLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptPaymentMethodLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReceiptPaymentMethodLabel.setText("PAYMENT METHOD:");

        GCASHitemLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        GCASHitemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GCASHitemLabel.setText("GCASH");

        ReceiptTrailingLines21.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines21.setText("------------------------------------");

        ThankYouLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ThankYouLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThankYouLabel.setText("THANK YOU FOR SHOPPING WITH US!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        GrandTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GrandTotalLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceiptTrailingLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReceiptAddress)
                    .addComponent(ReceiptTrailingLines1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ThankYouLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReceiptTrailingLines21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(ReceiptTrailingLines20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReceiptQuote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReceiptGrandTotalLabel)
                                    .addComponent(ReceiptItemLabel2)
                                    .addComponent(ReceiptPaymentMethodLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GCASHitemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GrandTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(ReceiptLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(ReceiptBrandName)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReceiptLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptBrandName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptTrailingLines)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptQuote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptTrailingLines1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptTrailingLines20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceiptGrandTotalLabel)
                    .addComponent(GrandTotalLabel))
                .addGap(6, 6, 6)
                .addComponent(ReceiptItemLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceiptPaymentMethodLabel)
                    .addComponent(GCASHitemLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptTrailingLines21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThankYouLabel)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GCASHitemLabel;
    public javax.swing.JLabel GrandTotalLabel;
    private javax.swing.JLabel ReceiptAddress;
    private javax.swing.JLabel ReceiptBrandName;
    private javax.swing.JLabel ReceiptGrandTotalLabel;
    private javax.swing.JLabel ReceiptItemLabel2;
    private javax.swing.JLabel ReceiptLogo;
    private javax.swing.JLabel ReceiptPaymentMethodLabel;
    private javax.swing.JLabel ReceiptQuote;
    private javax.swing.JLabel ReceiptTrailingLines;
    private javax.swing.JLabel ReceiptTrailingLines1;
    private javax.swing.JLabel ReceiptTrailingLines20;
    private javax.swing.JLabel ReceiptTrailingLines21;
    private javax.swing.JLabel ThankYouLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
