/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gameburza;

/**
 *
 * @author Jhan Steven Cruz
 */
public class GenerateReceipt extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReceipt
     */
    public GenerateReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReceiptLogo = new javax.swing.JLabel();
        ReceiptBrandName = new javax.swing.JLabel();
        ReceiptTrailingLines = new javax.swing.JLabel();
        ReceiptQuote = new javax.swing.JLabel();
        ReceiptAddress = new javax.swing.JLabel();
        ReceiptTrailingLines1 = new javax.swing.JLabel();
        ReceiptItemLabel = new javax.swing.JLabel();
        QTYItemLabel = new javax.swing.JLabel();
        ReceiptPriceLabel = new javax.swing.JLabel();
        ReceiptTotalLabel = new javax.swing.JLabel();
        ItemScrollPane = new javax.swing.JScrollPane();
        QtyScrollPane = new javax.swing.JScrollPane();
        TotalScrollPane = new javax.swing.JScrollPane();
        PriceScrollPane = new javax.swing.JScrollPane();
        ReceiptTrailingLines20 = new javax.swing.JLabel();
        ReceiptGrandTotalLabel = new javax.swing.JLabel();
        ReceiptItemLabel2 = new javax.swing.JLabel();
        ReceiptPaymentMethodLabel = new javax.swing.JLabel();
        GrandTotalPane = new javax.swing.JScrollPane();
        GCASHitemLabel = new javax.swing.JLabel();
        ReceiptTrailingLines21 = new javax.swing.JLabel();
        ThankYouLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReceiptLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameburza50x50.png"))); // NOI18N
        ReceiptLogo.setText("jLabel1");

        ReceiptBrandName.setFont(new java.awt.Font("Nebula", 0, 18)); // NOI18N
        ReceiptBrandName.setText("GAMEBURZA");

        ReceiptTrailingLines.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines.setText("------------------------------------");

        ReceiptQuote.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptQuote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptQuote.setText("CLICK IT, PLAY IT, OWN IT!");

        ReceiptAddress.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptAddress.setText("<html><div style=\"text-align: center;\">     704 Boni Avenue,  Barangay Malamig,<br>     Mandaluyong City, Metro Manila,<br>     Philippines </div></html>");

        ReceiptTrailingLines1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines1.setText("------------------------------------");

        ReceiptItemLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReceiptItemLabel.setText("ITEM");

        QTYItemLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        QTYItemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QTYItemLabel.setText("QTY");

        ReceiptPriceLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptPriceLabel.setText("PRICE");

        ReceiptTotalLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptTotalLabel.setText("TOTAL");

        ReceiptTrailingLines20.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines20.setText("------------------------------------");

        ReceiptGrandTotalLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptGrandTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReceiptGrandTotalLabel.setText("GRAND TOTAL:");

        ReceiptItemLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptItemLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ReceiptPaymentMethodLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptPaymentMethodLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReceiptPaymentMethodLabel.setText("PAYMENT METHOD:");

        GCASHitemLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        GCASHitemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GCASHitemLabel.setText("GCASH");

        ReceiptTrailingLines21.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ReceiptTrailingLines21.setText("------------------------------------");

        ThankYouLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ThankYouLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThankYouLabel.setText("THANK YOU FOR SHOPPING WITH US!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(ReceiptLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ReceiptBrandName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceiptTrailingLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReceiptAddress)
                    .addComponent(ReceiptTrailingLines1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ThankYouLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReceiptTrailingLines21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReceiptTrailingLines20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReceiptQuote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ItemScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReceiptItemLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(QtyScrollPane)
                                    .addComponent(QTYItemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PriceScrollPane)
                                    .addComponent(ReceiptPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReceiptTotalLabel))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReceiptGrandTotalLabel)
                                    .addComponent(ReceiptItemLabel2)
                                    .addComponent(ReceiptPaymentMethodLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GrandTotalPane)
                                    .addComponent(GCASHitemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReceiptLogo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptBrandName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptTrailingLines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptQuote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptTrailingLines1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReceiptItemLabel)
                            .addComponent(QTYItemLabel)
                            .addComponent(ReceiptPriceLabel)
                            .addComponent(ReceiptTotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemScrollPane)
                            .addComponent(QtyScrollPane)
                            .addComponent(TotalScrollPane)
                            .addComponent(PriceScrollPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptTrailingLines20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceiptGrandTotalLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(GrandTotalPane, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(ReceiptItemLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReceiptPaymentMethodLabel)
                    .addComponent(GCASHitemLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceiptTrailingLines21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThankYouLabel)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GCASHitemLabel;
    private javax.swing.JScrollPane GrandTotalPane;
    private javax.swing.JScrollPane ItemScrollPane;
    private javax.swing.JScrollPane PriceScrollPane;
    private javax.swing.JLabel QTYItemLabel;
    private javax.swing.JScrollPane QtyScrollPane;
    private javax.swing.JLabel ReceiptAddress;
    private javax.swing.JLabel ReceiptAddress1;
    private javax.swing.JLabel ReceiptAddress2;
    private javax.swing.JLabel ReceiptAddress3;
    private javax.swing.JLabel ReceiptAddress4;
    private javax.swing.JLabel ReceiptAddress5;
    private javax.swing.JLabel ReceiptAddress6;
    private javax.swing.JLabel ReceiptAddress7;
    private javax.swing.JLabel ReceiptAddress8;
    private javax.swing.JLabel ReceiptAddress9;
    private javax.swing.JLabel ReceiptBrandName;
    private javax.swing.JLabel ReceiptBrandName1;
    private javax.swing.JLabel ReceiptBrandName2;
    private javax.swing.JLabel ReceiptBrandName3;
    private javax.swing.JLabel ReceiptBrandName4;
    private javax.swing.JLabel ReceiptBrandName5;
    private javax.swing.JLabel ReceiptBrandName6;
    private javax.swing.JLabel ReceiptBrandName7;
    private javax.swing.JLabel ReceiptBrandName8;
    private javax.swing.JLabel ReceiptBrandName9;
    private javax.swing.JLabel ReceiptGrandTotalLabel;
    private javax.swing.JLabel ReceiptItemLabel;
    private javax.swing.JLabel ReceiptItemLabel2;
    private javax.swing.JLabel ReceiptLogo;
    private javax.swing.JLabel ReceiptLogo1;
    private javax.swing.JLabel ReceiptLogo2;
    private javax.swing.JLabel ReceiptLogo3;
    private javax.swing.JLabel ReceiptLogo4;
    private javax.swing.JLabel ReceiptLogo5;
    private javax.swing.JLabel ReceiptLogo6;
    private javax.swing.JLabel ReceiptLogo7;
    private javax.swing.JLabel ReceiptLogo8;
    private javax.swing.JLabel ReceiptLogo9;
    private javax.swing.JLabel ReceiptPaymentMethodLabel;
    private javax.swing.JLabel ReceiptPriceLabel;
    private javax.swing.JLabel ReceiptQuote;
    private javax.swing.JLabel ReceiptQuote10;
    private javax.swing.JLabel ReceiptQuote11;
    private javax.swing.JLabel ReceiptQuote12;
    private javax.swing.JLabel ReceiptQuote13;
    private javax.swing.JLabel ReceiptQuote14;
    private javax.swing.JLabel ReceiptQuote15;
    private javax.swing.JLabel ReceiptQuote16;
    private javax.swing.JLabel ReceiptQuote17;
    private javax.swing.JLabel ReceiptQuote18;
    private javax.swing.JLabel ReceiptQuote19;
    private javax.swing.JLabel ReceiptQuote20;
    private javax.swing.JLabel ReceiptQuote21;
    private javax.swing.JLabel ReceiptQuote22;
    private javax.swing.JLabel ReceiptQuote23;
    private javax.swing.JLabel ReceiptQuote24;
    private javax.swing.JLabel ReceiptQuote25;
    private javax.swing.JLabel ReceiptQuote26;
    private javax.swing.JLabel ReceiptQuote27;
    private javax.swing.JLabel ReceiptQuote28;
    private javax.swing.JLabel ReceiptQuote29;
    private javax.swing.JLabel ReceiptQuote30;
    private javax.swing.JLabel ReceiptQuote31;
    private javax.swing.JLabel ReceiptQuote32;
    private javax.swing.JLabel ReceiptQuote33;
    private javax.swing.JLabel ReceiptQuote34;
    private javax.swing.JLabel ReceiptQuote35;
    private javax.swing.JLabel ReceiptQuote36;
    private javax.swing.JLabel ReceiptQuote37;
    private javax.swing.JLabel ReceiptQuote38;
    private javax.swing.JLabel ReceiptQuote39;
    private javax.swing.JLabel ReceiptQuote40;
    private javax.swing.JLabel ReceiptQuote41;
    private javax.swing.JLabel ReceiptQuote42;
    private javax.swing.JLabel ReceiptQuote43;
    private javax.swing.JLabel ReceiptQuote44;
    private javax.swing.JLabel ReceiptQuote45;
    private javax.swing.JLabel ReceiptQuote46;
    private javax.swing.JLabel ReceiptQuote47;
    private javax.swing.JLabel ReceiptQuote48;
    private javax.swing.JLabel ReceiptQuote49;
    private javax.swing.JLabel ReceiptQuote5;
    private javax.swing.JLabel ReceiptQuote6;
    private javax.swing.JLabel ReceiptQuote7;
    private javax.swing.JLabel ReceiptQuote8;
    private javax.swing.JLabel ReceiptQuote9;
    private javax.swing.JLabel ReceiptTotalLabel;
    private javax.swing.JLabel ReceiptTrailingLines;
    private javax.swing.JLabel ReceiptTrailingLines1;
    private javax.swing.JLabel ReceiptTrailingLines10;
    private javax.swing.JLabel ReceiptTrailingLines11;
    private javax.swing.JLabel ReceiptTrailingLines12;
    private javax.swing.JLabel ReceiptTrailingLines13;
    private javax.swing.JLabel ReceiptTrailingLines14;
    private javax.swing.JLabel ReceiptTrailingLines15;
    private javax.swing.JLabel ReceiptTrailingLines16;
    private javax.swing.JLabel ReceiptTrailingLines17;
    private javax.swing.JLabel ReceiptTrailingLines18;
    private javax.swing.JLabel ReceiptTrailingLines19;
    private javax.swing.JLabel ReceiptTrailingLines2;
    private javax.swing.JLabel ReceiptTrailingLines20;
    private javax.swing.JLabel ReceiptTrailingLines21;
    private javax.swing.JLabel ReceiptTrailingLines3;
    private javax.swing.JLabel ReceiptTrailingLines4;
    private javax.swing.JLabel ReceiptTrailingLines5;
    private javax.swing.JLabel ReceiptTrailingLines6;
    private javax.swing.JLabel ReceiptTrailingLines7;
    private javax.swing.JLabel ReceiptTrailingLines8;
    private javax.swing.JLabel ReceiptTrailingLines9;
    private javax.swing.JLabel ThankYouLabel;
    private javax.swing.JScrollPane TotalScrollPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
