/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gameburza;

/**
 *
 * @author sean
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     */
    public ItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemPricePanel = new javax.swing.JLabel();
        GTAVButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(200, 300));

        ItemPricePanel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        ItemPricePanel.setText("Price");

        GTAVButton.setBackground(new java.awt.Color(255, 153, 153));
        GTAVButton.setFont(new java.awt.Font("Nebula", 0, 10)); // NOI18N
        GTAVButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GTAVlogo (2).png"))); // NOI18N
        GTAVButton.setText("GTa V SOBRaNG GaNDa");
        GTAVButton.setBorderPainted(false);
        GTAVButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GTAVButton.setIconTextGap(10);
        GTAVButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        GTAVButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        GTAVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GTAVButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(ItemPricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(GTAVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GTAVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(ItemPricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GTAVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GTAVButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GTAVButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GTAVButton;
    private javax.swing.JLabel ItemPricePanel;
    // End of variables declaration//GEN-END:variables
}
